# Generated by Django 5.1 on 2024-10-24 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('velocidad', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo_desarrollo', models.ManyToManyField(blank=True, related_name='equipo_desarrollo', to=settings.AUTH_USER_MODEL)),
                ('scrum_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('criterios_aceptacion', models.TextField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('POR_HACER', 'Por hacer'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], default='POR_HACER', max_length=20)),
                ('esfuerzo_estimado', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bloqueadores', models.TextField(blank=True, null=True)),
                ('dependencias', models.ManyToManyField(blank=True, to='scrum.tarea')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sprint_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrum.sprint')),
            ],
        ),
        migrations.AddField(
            model_name='sprint',
            name='backlog_sprint',
            field=models.ManyToManyField(blank=True, to='scrum.tarea'),
        ),
        migrations.CreateModel(
            name='Epica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('criterios_aceptacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('POR_HACER', 'Por hacer'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], default='POR_HACER', max_length=20)),
                ('esfuerzo_estimado_total', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('progreso', models.FloatField(default=0.0)),
                ('dependencias', models.ManyToManyField(blank=True, to='scrum.epica')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tareas_asociadas', models.ManyToManyField(blank=True, to='scrum.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='TareaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.tarea')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('prioridad__gte', 0)), name='prioridad_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('esfuerzo_estimado__gte', 0)), name='esfuerzo_estimado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['POR_HACER', 'EN_PROGRESO', 'COMPLETADA'])), name='estado_valido_tarea'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='fecha_fin_posterior'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.CheckConstraint(condition=models.Q(('velocidad__gte', 0)), name='velocidad_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='epica',
            constraint=models.CheckConstraint(condition=models.Q(('esfuerzo_estimado_total__gte', 0)), name='esfuerzo_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='epica',
            constraint=models.CheckConstraint(condition=models.Q(('progreso__gte', 0), ('progreso__lte', 1)), name='progreso_valido'),
        ),
        migrations.AddConstraint(
            model_name='epica',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='fecha_fin_posterior_epica'),
        ),
        migrations.AddConstraint(
            model_name='epica',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['POR_HACER', 'EN_PROGRESO', 'COMPLETADA'])), name='estado_valido_epica'),
        ),
    ]
