# Generated by Django 5.1 on 2024-11-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_tareahistorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'permissions': [('listar_tareas', 'Puede listar las tareas')]},
        ),
    ]
